spring:
    thymeleaf:
        cache: false
        suffix: .html
        encoding: utf-8
        content-type: text/html
        mode: HTML5

    datasource:
        url: jdbc:mysql://localhost:3306/glsc_auth?characterEncoding=utf8&useSSL=false
        username: root
        password: Weiyang#0
        driver-class-name: com.mysql.jdbc.Driver

    redis:
        database: 0         # Redis数据库索引(默认为0)
        host: localhost
        port: 6379
        password:
        pool:
            max-active: 8     # 连接池最大连接数
            max-wait: -1      # 最大阻塞等待时间， -1表示没有限制
            max-idle: 8       # 最大空闲连接
            min-idle: 0       # 最小空闲连接
        timeout: 0            # 连接超时时间(毫秒)

logging:
  path: /Users/everseeker/Log/glsc_auth
  level:
    root: INFO
    org.springframework.web: INFO

#    不采用mongodb的主要原因：不支持事务
#    data:
#        mongodb:
#            uri: localhost:27017/glsc
#            username: glsc
#            password: glsc1212
#            authentication-database: glsc
